- name: Execute MySQL Setup Commands
  hosts: localhost
  become: yes
  vars:
    mysql_root_password: "your_root_password"
    mysql_user: "quiz_user"
    mysql_user_password: "password"
    mysql_database: "quizdb"

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-pip
          - mysql-server
        state: present
        update_cache: yes

    - name: Install PyMySQL
      pip:
        name: pymysql

    - name: Start and enable MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Update MySQL bind-address
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'
      notify: Restart MySQL

    - name: Ensure MySQL root password is set
      community.mysql.mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create MySQL database
      community.mysql.mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user and grant privileges
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create `user` table
      community.mysql.mysql_query:
        query: >
          CREATE TABLE IF NOT EXISTS user (
          id INT AUTO_INCREMENT PRIMARY KEY,
          username VARCHAR(255) NOT NULL,
          password VARCHAR(512) NOT NULL,
          is_admin TINYINT(1) NOT NULL
          );
        login_db: "{{ mysql_database }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create `topic` table
      community.mysql.mysql_query:
        query: >
          CREATE TABLE IF NOT EXISTS topic (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(100) NOT NULL UNIQUE
          );
        login_db: "{{ mysql_database }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create `quiz` table
      community.mysql.mysql_query:
        query: >
          CREATE TABLE IF NOT EXISTS quiz (
          id INT AUTO_INCREMENT PRIMARY KEY,
          question TEXT NOT NULL,
          option1 VARCHAR(255) NOT NULL,
          option2 VARCHAR(255) NOT NULL,
          option3 VARCHAR(255) NOT NULL,
          option4 VARCHAR(255) NOT NULL,
          correct_option INT NOT NULL
          );
        login_db: "{{ mysql_database }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"

  handlers:
    - name: Restart MySQL
      systemd:
        name: mysql
        state: restarted
